# Default configuration for collaborative-docs backend

[server]
host = "0.0.0.0"
port = 3000

[database]
url = "postgresql://postgres:password@localhost:5432/collaborative_docs"

[cors]
allowed_origins = [
    "http://localhost:5173",
    "http://localhost:3000"
]
allowed_methods = [
    "GET",
    "POST", 
    "PUT",
    "DELETE"
] 