# Production configuration
# Note: In production, most values should be overridden by environment variables

[server]
host = "0.0.0.0"
port = 3000

[database]
host = "localhost"
port = 5432
username = "postgres"
password = "CHANGE_ME_IN_PRODUCTION"
database = "collaborative_docs"
max_connections = 20
min_connections = 5

[cors]
allowed_origins = [
    "https://yourdomain.com",
    "https://www.yourdomain.com"
]
allowed_methods = [
    "GET",
    "POST", 
    "PUT"
] 