# Production configuration
# Note: In production, most values should be overridden by environment variables

[server]
host = "0.0.0.0"
port = 3000

[database]
url = "postgresql://postgres:password@localhost:5432/collaborative_docs"

[cors]
allowed_origins = [
    "https://yourdomain.com",
    "https://www.yourdomain.com"
]
allowed_methods = [
    "GET",
    "POST", 
    "PUT"
] 