# Development configuration

[server]
host = "0.0.0.0"
port = 3000

[database]
host = "localhost"
port = 5432
username = "postgres"
password = "password"
database = "collaborative_docs_dev"
max_connections = 5
min_connections = 1

[cors]
allowed_origins = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000"
]
allowed_methods = [
    "GET",
    "POST", 
    "PUT",
    "DELETE",
    "OPTIONS"
] 